name: Nightly Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: windows-2019

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup MSBuild
      uses: warrenbuckley/Setup-MSBuild@v1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    - name: Restore NuGet Packages (build)
      run: dotnet restore src\BrockAllen.MembershipReboot.sln

    - name: Restore NuGet Packages (solution)
      run: nuget restore src\BrockAllen.MembershipReboot.sln

    - name: Build
      run: msbuild src\BrockAllen.MembershipReboot.sln /p:Configuration=Debug